### ISSUE TITLE
[BUG]: message box not showing correctly

### ISSUE THREAD

**Issue by codingbaobao** [eideehi/sd-webui-better-styles#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

the message box from save style isn't showing correctly in the newest webui(hash: 280ed8f00fde0ece026339acdd42888ac4dc3167).
most of text are not showing correctly. Please see the screenshot below.

### Steps to Reproduce

1. click save style, and thats it.
2. click the information on the style card (the icon on the top right of card), and all empty.

### Screenshot (optional)

<img width="536" alt="image" src="https://user-images.githubusercontent.com/22337217/230009926-9e0d67d0-0b56-4669-b43f-508e6a1a703e.png">
<img width="536" alt="image" src="https://user-images.githubusercontent.com/22337217/230010833-d03edd19-1c95-4df2-a72e-f5c408a7b378.png">

**Comment by eideehi** [comment]
I would like to inform you that Better Styles version 1.1.0 (e4737341646f729474b681385922814392207b12) or later will not function properly as it has been developed on WebUI 22bcc7be428c94e9408f589966c2040187245d81. Therefore, please either use Better Styles version 1.0.1 (444b242c0ce525a8356be81634d3fb65002e39c2) or upgrade your WebUI version.

![github](https://user-images.githubusercontent.com/41231321/230128831-f6f69de6-b5b1-41b4-9bef-851540e6607c.png)

**Comment by codingbaobao** [comment]
I am sure I have up-to-date my WebUI, but i don't see any feature related 😢
Also, it may be great if you mention these things on README.

**Comment by eideehi** [comment]
I have added a description about version changes to the README.

https://github.com/eideehi/sd-webui-better-styles/blob/main/README.adoc#using-a-different-version
