### ISSUE TITLE
[FEATURE]: Import stiles from default styles.csv

### ISSUE THREAD

**Issue by GlebIgorevich** [eideehi/sd-webui-better-styles#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature is needed?

Need a tool for interaction with styles in the default styles.csv.

It may be implemented in one of these ways:
1. Best way: interact with styles.csv. When the user applies the style in your extension you take the style from styles.csv and add data from the preset (sampler, steps, cfg, etc). Your extension keeps the pairs "style from row X" + "preset, preview, folder"
2. Simple and not a good way: just import all the styles from styles.csv.

### Why is the feature needed and how it will be used?

If a user is not newbie he has many custom styles. Without ways for merging or importing that your extension is not helpful.

**Comment by eideehi** [comment]
The feature itself has been implemented in 1.3.0. It has now become practical with the 1.4.0 update, so we will close it.
