### ISSUE TITLE
[FEATURE]: Add setting to disable expansion of better-styles by default

### ISSUE THREAD

**Issue by dragos240** [eideehi/sd-webui-better-styles#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature is needed?

It would be nice if better-styles didn't automatically expand on initial page load (or at least remember its previous state). I like to reduce clutter and while the extension is very useful, I don't want it to expand when on initial page load

### Why is the feature needed and how it will be used?

Giving users the option to hide better-styles on page load would reduce visual clutter and provide a better user experience.

**Comment by eideehi** [comment]
In today's release version 1.3.0, this option has been added.
