### ISSUE TITLE
[BUG]: Doesn't work with Vlad fork because localization object is not defined.

### ISSUE THREAD

**Issue by Aptronymist** [eideehi/sd-webui-better-styles#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Refuses to load in vlad fork, gives error below in firefox.
Uncaught (in promise) ReferenceError: localization is not defined
    Dn http://127.0.0.1:7860/file=extensions/sd-webui-better-styles/javascript/betterStyles.js?1684803623.031734:6
    
Corrected thanks to chatgpt.
added const localization = {}; to the start of your BetterStyles.js
Looking forward to trying it, hopefully that was enough to get it going.

### Steps to Reproduce

Install, try to use. Doesn't show up. Error in dev console.

**Comment by Gerkinfeltser** [comment]
@Aptronymist ChatGPT suggested fix did the trick for me.
`const localization = {};` to the start of your betterStyles.js gets the little icon to show up.

**Comment by Aptronymist** [comment]
In my case I now have it right after the first var, so like this:
var BetterStyles=function(){"use strict";const localization = {};
and make sure to have the "hide original styles" checked, as well as having 1.2.0 selected. I don't know for sure what fixes what beyond the localization addition, but those are my current settings and it works fine.

**Comment by brknsoul** [comment]
Note: Egg on face time;
Placing my extensions behind a symlink caused a lot of issues. Those issues vanished when I removed the symlink and copied the extension back to the main folder.

Closeable.
