### ISSUE TITLE
[FEATURE]: Editing styles in the WebUI

### ISSUE THREAD

**Issue by GlebIgorevich** [eideehi/sd-webui-better-styles#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature is needed?

Need a simple way for editing existing styles. It may look like adding the new style, because different scenarios may include changing parts or prompts to sampler and CFG or folder.
The feature of duplicating style will be good too.

### Why is the feature needed and how it will be used?

This feature is very important because the actual tools have no simple ways of editing the styles. Editing the unformatted json is not a user-friendly way.

**Comment by eideehi** [comment]
As mentioned in the README, it is possible to overwrite existing styles by entering the same name in the "Style name" field of the "Save style" form. Therefore, you can achieve your goal by following these steps: apply the desired style using "Apply style," modify the style in the Web UI, and overwrite the style using "Save style."

I will add the duplication feature of styles to the TODO list.
- [ ] Add the feature to duplicate styles.

**Comment by eideehi** [comment]
I will consider redesigning the UI of Better Styles.
- [ ] Redesign UI

On a side note, it is crucial to go through documentation such as the README, not just for Better Styles but for any project. This is especially important when you have concerns or questions about the functionality, as in this case. While I don't enjoy writing extensive documentation and have only provided the minimum, some authors go the extra mile and describe even the smallest details of the features, which can be incredibly helpful.

**Comment by eideehi** [comment]
I have made improvements in version 1.4.0 to enable more intuitive management of styles.
